# Generated by Django 4.2.7 on 2023-11-29 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_formulario', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'formulario',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('datanasc', models.DateField()),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('departamento', models.ForeignKey(db_column='id_departamento', null=True, on_delete=django.db.models.deletion.CASCADE, to='appqmemoria.departamento')),
                ('perfil', models.ForeignKey(db_column='id_perfil', null=True, on_delete=django.db.models.deletion.CASCADE, to='appqmemoria.perfil')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='PerfilFormulario',
            fields=[
                ('id_perfilformulario', models.AutoField(primary_key=True, serialize=False)),
                ('permissao', models.CharField(default='N', max_length=1)),
                ('formulario', models.ForeignKey(db_column='id_formulario', null=True, on_delete=django.db.models.deletion.CASCADE, to='appqmemoria.formulario')),
                ('perfil', models.ForeignKey(db_column='id_perfil', null=True, on_delete=django.db.models.deletion.CASCADE, to='appqmemoria.perfil')),
            ],
            options={
                'db_table': 'perfilformulario',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('sexo', models.CharField(max_length=80)),
                ('foto', models.CharField(max_length=255)),
                ('foto64', models.TextField()),
                ('campooculto', models.CharField(max_length=80)),
                ('datanasc', models.DateTimeField(blank=True, null=True)),
                ('cpf', models.CharField(max_length=14)),
                ('cep', models.CharField(max_length=30)),
                ('cnpj', models.CharField(max_length=30)),
                ('fone', models.CharField(max_length=14)),
                ('ativo', models.BooleanField(default=False)),
                ('cor', models.CharField(max_length=14)),
                ('texto', models.TextField()),
                ('idade', models.IntegerField(default=0)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('textolongo', models.TextField()),
                ('perfil', models.ForeignKey(db_column='id_perfil', null=True, on_delete=django.db.models.deletion.CASCADE, to='appqmemoria.perfil')),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
    ]
