# Generated by Django 4.2.6 on 2023-11-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appqmemoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id_teste', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'teste',
            },
        ),
    ]
