# Generated by Django 5.0 on 2023-12-26 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id_formulario', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'formulario',
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id_hotel', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('nomefantasia', models.CharField(max_length=80)),
                ('cnpj', models.CharField(max_length=80)),
                ('endereco', models.CharField(max_length=80)),
                ('numero', models.CharField(max_length=80)),
                ('bairro', models.CharField(max_length=80)),
                ('cidade', models.CharField(max_length=80)),
                ('estado', models.CharField(max_length=80)),
                ('responsavel', models.CharField(max_length=80)),
                ('fone', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'hotel',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=80)),
            ],
            options={
                'db_table': 'perfil',
            },
        ),
        migrations.CreateModel(
            name='Hospede',
            fields=[
                ('id_hospede', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('foto', models.CharField(max_length=255)),
                ('fone', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=80)),
                ('datanasc', models.DateField()),
                ('pai', models.CharField(max_length=80)),
                ('mae', models.CharField(max_length=80)),
                ('quarto', models.CharField(max_length=80)),
                ('entrada', models.DateTimeField()),
                ('saida', models.DateTimeField()),
                ('placa', models.CharField(max_length=80)),
                ('marca', models.CharField(max_length=80)),
                ('modelo', models.CharField(max_length=80)),
                ('cor', models.CharField(max_length=80)),
                ('hotel', models.ForeignKey(db_column='id_hotel', on_delete=django.db.models.deletion.CASCADE, to='appqmemoria.hotel')),
            ],
            options={
                'db_table': 'hospede',
            },
        ),
        migrations.CreateModel(
            name='PerfilFormulario',
            fields=[
                ('id_perfilformulario', models.AutoField(primary_key=True, serialize=False)),
                ('permissao', models.CharField(default='N', max_length=1)),
                ('formulario', models.ForeignKey(db_column='id_formulario', null=True, on_delete=django.db.models.deletion.CASCADE, to='appqmemoria.formulario')),
                ('perfil', models.ForeignKey(db_column='id_perfil', null=True, on_delete=django.db.models.deletion.CASCADE, to='appqmemoria.perfil')),
            ],
            options={
                'db_table': 'perfilformulario',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=80)),
                ('datanasc', models.DateField()),
                ('email', models.CharField(max_length=255)),
                ('senha', models.CharField(max_length=255)),
                ('hotel', models.ForeignKey(db_column='id_hotel', on_delete=django.db.models.deletion.CASCADE, to='appqmemoria.hotel')),
                ('perfil', models.ForeignKey(db_column='id_perfil', on_delete=django.db.models.deletion.CASCADE, to='appqmemoria.perfil')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
